##
##	Makefile for top-level module formatter project.
##  This makefile simply calls the lower level makefiles
##


all world : dummy
	( cd "src" ; make -f Makefile.Darwin ) ; \
	( cd "moduleSrc" ; make -f Makefile.Darwin )

clean : dummy
	SCRIPTDIR=`pwd`; \
	( cd "src" ; make -f Makefile.Darwin clean ) ; \
	( cd "moduleSrc" ; make -f Makefile.Darwin clean )

dummy :


